spring.application.name=stockpro-back

# ===============================
# Base de données PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_stock
spring.datasource.username=postgres
spring.datasource.password=admin123

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# Serveur
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=VW5lQ2xlU2VjcmV0ZVRyZXNMb25ndWVQb3VyU3RvY2tQcm9KV1RIUzI1NlNlY3VyaXNlZTIwMjY=
jwt.expiration-ms=86400000

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html